//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ID { get; set; }
        public string VIN { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public string Model { get; set; }
        public int LocationId { get; set; }
        public int FuelId { get; set; }
        public int GearboxId { get; set; }
        public int Odometer { get; set; }
        public Nullable<int> YearOfProduction { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual Gearbox Gearbox { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
